#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    num=arr[-1]
    def printt():
        for item in arr:
            print(item,end=' ')
        print()
    for i in range(n-1,-1,-1):
        if i-1>=0 and num<arr[i-1]:
            arr[i]=arr[i-1]
            printt()
        else:
            arr[i]=num
            printt()
            break

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
